In [ ]:
import numpy as np

# create 3D array with value = 25 all cell 
data = np.full((3, 4, 5), 25)

print("3D array with all values set to 25:"
      "\n", data)




3D array with all values set to 25:
 [[[25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]]

 [[25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]]

 [[25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]]]
Mean of 3D array along axis 0:
[[25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]]

Mean of 2D array along axis 0:
[0.59273278 0.7448015  0.30071564 0.32557941]
